# WireGuard mesh - redfin (10.100.0.1)
# Cherokee AI Federation - Generated 2026-02-24

[Interface]
Address = 10.100.0.1/24
ListenPort = 51820
PostUp = wg set %i private-key /etc/wireguard/privatekey
SaveConfig = false

# bluefin
[Peer]
PublicKey = XL7KXdm6owyliup9Z9RGmNEYS/h65U+2ZeqzxUNlMEg=
PresharedKey = cZPlXXu9xNDiisixi/TcQnc8mMfZ0xjoo3w/wyZOuDc=
AllowedIPs = 10.100.0.2/32
Endpoint = 192.168.132.222:51820
PersistentKeepalive = 25

# greenfin
[Peer]
PublicKey = k9iZPiPaDuB7ZEHSdhtjuepM8JYUNLY3moeZW+Oa2EQ=
PresharedKey = rj5U7vpCmQjCd7Mjoxp16ZKxEGARU8gHRoEMcspWTKM=
AllowedIPs = 10.100.0.3/32
Endpoint = 192.168.132.224:51820
PersistentKeepalive = 25

# owlfin
[Peer]
PublicKey = w/KcYH808SNXX3Q2FHp0yrs/WLe7X92T9yTSM7Vp2Rk=
PresharedKey = wAiwQ9dK0VwHlt8+f063eMjmGCpLikQUSBtED6K7Nbg=
AllowedIPs = 10.100.0.5/32
Endpoint = 192.168.132.170:51820
PersistentKeepalive = 25

# eaglefin
[Peer]
PublicKey = lgj+LiP5S+QiYQgWKS8iY66YK+REKcGbv9N8L4AABFA=
PresharedKey = 1ZvUGckfEcYvJIWNmrf4B5rQQbymtvJk/LGxi7jZ8tY=
AllowedIPs = 10.100.0.6/32
Endpoint = 192.168.132.84:51820
PersistentKeepalive = 25
