# WireGuard mesh - owlfin (10.100.0.5)
# Cherokee AI Federation - Generated 2026-02-24

[Interface]
Address = 10.100.0.5/24
ListenPort = 51820
PostUp = wg set %i private-key /etc/wireguard/privatekey
SaveConfig = false

# redfin
[Peer]
PublicKey = rx/iI9OUyt2xcuaKUFnoB5BCqTi1EOMuh6cvD3MX5QU=
PresharedKey = wAiwQ9dK0VwHlt8+f063eMjmGCpLikQUSBtED6K7Nbg=
AllowedIPs = 10.100.0.1/32
Endpoint = 192.168.132.223:51820
PersistentKeepalive = 25

# bluefin
[Peer]
PublicKey = XL7KXdm6owyliup9Z9RGmNEYS/h65U+2ZeqzxUNlMEg=
PresharedKey = OOz8ph3ztbHinCvikGJ7hCQm1m1DG7pQUVbCeCTMC5E=
AllowedIPs = 10.100.0.2/32
Endpoint = 192.168.132.222:51820
PersistentKeepalive = 25

# greenfin
[Peer]
PublicKey = k9iZPiPaDuB7ZEHSdhtjuepM8JYUNLY3moeZW+Oa2EQ=
PresharedKey = 2zMkXNX6itIKEXbH5m1Mkpyj3ym0+eHtVeUo3etT4cg=
AllowedIPs = 10.100.0.3/32
Endpoint = 192.168.132.224:51820
PersistentKeepalive = 25

# eaglefin
[Peer]
PublicKey = lgj+LiP5S+QiYQgWKS8iY66YK+REKcGbv9N8L4AABFA=
PresharedKey = h/tYBfbEbhtPltWHUzln2GZC1caUSgYzL0Q8cIqWbfU=
AllowedIPs = 10.100.0.6/32
Endpoint = 192.168.132.84:51820
PersistentKeepalive = 25
