# WireGuard mesh - bluefin (10.100.0.2)
# Cherokee AI Federation - Generated 2026-02-24

[Interface]
Address = 10.100.0.2/24
ListenPort = 51820
PostUp = wg set %i private-key /etc/wireguard/privatekey
SaveConfig = false

# redfin
[Peer]
PublicKey = rx/iI9OUyt2xcuaKUFnoB5BCqTi1EOMuh6cvD3MX5QU=
PresharedKey = cZPlXXu9xNDiisixi/TcQnc8mMfZ0xjoo3w/wyZOuDc=
AllowedIPs = 10.100.0.1/32
Endpoint = 192.168.132.223:51820
PersistentKeepalive = 25

# greenfin
[Peer]
PublicKey = k9iZPiPaDuB7ZEHSdhtjuepM8JYUNLY3moeZW+Oa2EQ=
PresharedKey = POhJkVis9rrWBKTdXsa9FdqvO4nPf1k2lstMEXUg/M4=
AllowedIPs = 10.100.0.3/32
Endpoint = 192.168.132.224:51820
PersistentKeepalive = 25

# owlfin
[Peer]
PublicKey = w/KcYH808SNXX3Q2FHp0yrs/WLe7X92T9yTSM7Vp2Rk=
PresharedKey = OOz8ph3ztbHinCvikGJ7hCQm1m1DG7pQUVbCeCTMC5E=
AllowedIPs = 10.100.0.5/32
Endpoint = 192.168.132.170:51820
PersistentKeepalive = 25

# eaglefin
[Peer]
PublicKey = lgj+LiP5S+QiYQgWKS8iY66YK+REKcGbv9N8L4AABFA=
PresharedKey = TZ+FULjn+Pqdx62n9jUE2z3bNGKB9VHrx8yTecUjaqo=
AllowedIPs = 10.100.0.6/32
Endpoint = 192.168.132.84:51820
PersistentKeepalive = 25
