name: ganuda
description: Cherokee Digital Sovereignty - Quantum Crawdad Network Optimization
version: 0.1.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core functionality
  connectivity_plus: ^5.0.0
  network_info_plus: ^4.1.0
  permission_handler: ^11.0.0
  geolocator: ^10.1.0
  
  # State management
  provider: ^6.1.0
  
  # Storage
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # UI
  cupertino_icons: ^1.0.6
  fl_chart: ^0.65.0
  lottie: ^2.7.0
  
  # Testing mock devices
  device_preview: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.0
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/sounds/
  
  fonts:
    - family: Cherokee
      fonts:
        - asset: assets/fonts/Cherokee.ttf