#!/bin/bash
echo "🍎 DEPLOY QUANTUM CRAWDAD TO MAC (AT&T FIBER)"
echo "=============================================="
echo ""
echo "Your Mac 'asshat2' has AT&T fiber - perfect for Robinhood!"
echo ""
echo "QUICK DEPLOYMENT:"
echo "-----------------"
echo "1. Copy the trading bot to your Mac:"
echo ""
echo "scp -r /home/dereadi/scripts/claude/robin_stocks user@192.168.132.71:~/quantum_crawdad/"
echo "scp /home/dereadi/scripts/claude/robinhood_session_trader.py user@192.168.132.71:~/"
echo "scp /home/dereadi/scripts/claude/.env user@192.168.132.71:~/"
echo ""
echo "2. On your Mac, install requirements:"
echo ""
echo "pip3 install robin-stocks pyotp python-dotenv yfinance requests"
echo ""
echo "3. Run from your Mac (with AT&T IP):"
echo ""
echo "python3 robinhood_session_trader.py"
echo ""
echo "=============================================="
echo "ALTERNATIVE: Remote control from here"
echo ""
echo "ssh user@192.168.132.71 'cd ~/ && python3 robinhood_session_trader.py'"
echo ""
echo "This runs on your Mac but you control it from here!"
echo "=============================================="