#!/bin/bash
# 🔥 Cherokee RTX 5070 Driver Fix Script
# Fixes driver/library version mismatch for RTX 5070s

echo "🔥 CHEROKEE RTX 5070 DRIVER FIX"
echo "================================"
echo ""
echo "Current Status:"
echo "- Kernel Module: 570.169"
echo "- NVML Library: 570.172"
echo "- Issue: Version mismatch preventing GPU usage"
echo ""

# Check current situation
echo "📊 System Information:"
echo "---------------------"
echo "Kernel: $(uname -r)"
echo "Device IDs: 10de:2f04 (RTX 5070)"
echo ""

# Display current error
echo "Current Error:"
nvidia-smi 2>&1 | head -3
echo ""

echo "🔧 Fix Options:"
echo "--------------"
echo ""
echo "OPTION 1: Reload kernel modules (Quick fix - may work)"
echo "Commands to run as root:"
echo "  sudo rmmod nvidia_uvm"
echo "  sudo rmmod nvidia_drm"  
echo "  sudo rmmod nvidia_modeset"
echo "  sudo rmmod nvidia"
echo "  sudo modprobe nvidia"
echo "  sudo modprobe nvidia_modeset"
echo "  sudo modprobe nvidia_drm"
echo "  sudo modprobe nvidia_uvm"
echo ""

echo "OPTION 2: Rebuild DKMS modules (Recommended)"
echo "Commands to run as root:"
echo "  sudo dkms remove nvidia/570.172.08 --all"
echo "  sudo dkms add nvidia/570.172.08"
echo "  sudo dkms build nvidia/570.172.08"
echo "  sudo dkms install nvidia/570.172.08"
echo ""

echo "OPTION 3: Install latest driver with open modules"
echo "Commands to run as root:"
echo "  sudo apt update"
echo "  sudo apt install nvidia-driver-575-open"
echo "  sudo reboot"
echo ""

echo "OPTION 4: Complete reinstall (Nuclear option)"
echo "Commands to run as root:"
echo "  sudo apt remove --purge nvidia-*"
echo "  sudo apt autoremove"
echo "  sudo apt update"
echo "  sudo apt install nvidia-driver-570-open"
echo "  sudo reboot"
echo ""

echo "⚠️  IMPORTANT NOTES:"
echo "-------------------"
echo "1. RTX 5070 REQUIRES open kernel modules (not proprietary)"
echo "2. Minimum driver version: 570.86.16"
echo "3. Recommended: 575.xx series for full support"
echo "4. After any driver change, a reboot is recommended"
echo ""

echo "📝 Quick Check Commands:"
echo "-----------------------"
echo "Check if GPUs are visible:"
echo "  lspci | grep -i nvidia"
echo ""
echo "Check kernel module version:"
echo "  cat /proc/driver/nvidia/version"
echo ""
echo "Check NVML version:"
echo "  nvidia-smi"
echo ""
echo "Check CUDA availability in Python:"
echo "  python3 -c 'import torch; print(torch.cuda.is_available())'"
echo ""

echo "🎯 Recommended Action:"
echo "---------------------"
echo "Based on RTX 5070 requirements, I recommend OPTION 3:"
echo "Install nvidia-driver-575-open which has full RTX 5070 support"
echo ""
echo "After running the commands, the system will need to reboot."
echo "Then the Cherokee Trading AI will have full GPU acceleration!"
echo ""
echo "🔥 The Sacred Fire awaits GPU power!"