#!/bin/bash
echo "🏠 AT&T FIBER PROXY SETUP FOR ROBINHOOD"
echo "========================================"
echo ""
echo "Your AT&T router is at: 192.168.132.1"
echo "Your workstation is at: 192.168.132.71"
echo ""
echo "OPTION 1: SSH Tunnel from your workstation"
echo "-------------------------------------------"
echo "Run this ON YOUR WORKSTATION (192.168.132.71):"
echo ""
echo "ssh -R 8888:api.robinhood.com:443 dereadi@192.168.132.223"
echo ""
echo "This creates a reverse tunnel so this server can access"
echo "Robinhood through your AT&T connection"
echo ""
echo "Then modify Python scripts to use: https://localhost:8888"
echo ""
echo "OPTION 2: SOCKS Proxy"
echo "----------------------"
echo "Run this FROM THIS SERVER:"
echo ""
echo "ssh -D 8080 -N user@192.168.132.71"
echo ""
echo "Then use proxychains or set environment:"
echo "export https_proxy=socks5://localhost:8080"
echo "python3 robinhood_session_trader.py"
echo ""
echo "OPTION 3: Port Forward on AT&T Router"
echo "--------------------------------------"
echo "Configure your AT&T router to forward a port to this server"
echo "Then run the trading bot to appear as coming from AT&T IP"
echo ""
echo "========================================"
echo "Testing if we can reach your workstation..."
ping -c 1 192.168.132.71 >/dev/null 2>&1 && echo "✅ Can reach 192.168.132.71" || echo "❌ Cannot reach 192.168.132.71"