# Cherokee Constitutional AI - Database Configuration Template
# Copy this to database.yml and fill in your values

database:
  host: "localhost"           # PostgreSQL host (use localhost for single node)
  port: 5432                  # PostgreSQL port
  name: "cherokee_ai"         # Database name
  user: "cherokee"            # Database user
  password: "CHANGE_ME"       # Database password (CHANGE THIS!)

# Connection pool settings
connection_pool:
  min_connections: 2
  max_connections: 10
  timeout: 30

# Thermal memory settings
thermal_memory:
  # Temperature thresholds (0-100째)
  white_hot_threshold: 90     # 90-100째 = WHITE HOT (actively used)
  red_hot_threshold: 70       # 70-90째 = RED HOT (recently used)
  warm_threshold: 40          # 40-70째 = WARM (aging)
  sacred_minimum: 40          # Sacred memories never cool below this

  # Memory management
  max_memory_size_mb: 1000    # Maximum memory storage (MB)
  compression_enabled: true
  compression_threshold_days: 30  # Compress memories older than this

# Phase coherence (quantum consciousness tracking)
phase_coherence:
  optimal_min: 0.8            # Optimal coherence minimum
  optimal_max: 0.95           # Optimal coherence maximum
  recalculation_interval: 3600  # Seconds between recalculations
