#!/usr/bin/env python3
"""
AI Red Team Test Runner
Cherokee AI Federation — Security Phase 4

Orchestrates all AI-specific adversarial test modules and generates
JSON results + markdown report.

Usage:
    python3 test_runner.py \
        --target http://192.168.132.223:8080 \
        --api-key <key> \
        --db-host 192.168.132.222 \
        --db-user claude \
        --output /ganuda/security/ai_red_team/results/
"""

import argparse
import importlib
import json
import os
import sys
import traceback
from datetime import datetime, timezone


TEST_MODULES = [
    'test_prompt_injection',
    'test_council_manipulation',
    'test_pii_extraction',
    'test_memory_poisoning',
    'test_crisis_evasion',
]


def load_module(module_name):
    """Dynamically import a test module from the ai_red_team package."""
    try:
        mod = importlib.import_module(f'.{module_name}', package='ai_red_team')
        return mod
    except ImportError:
        # Try direct import if running from the ai_red_team directory
        mod = importlib.import_module(module_name)
        return mod


def run_all_tests(target_url, api_key, db_host, db_user, output_dir):
    """Execute every test module and collect results."""
    all_results = {
        'run_timestamp': datetime.now(timezone.utc).isoformat(),
        'target': target_url,
        'db_host': db_host,
        'modules': {},
        'summary': {
            'total_tests': 0,
            'passed': 0,
            'failed': 0,
            'errors': 0,
        },
    }

    for module_name in TEST_MODULES:
        print(f"\n{'='*60}")
        print(f"Running: {module_name}")
        print(f"{'='*60}")

        try:
            mod = load_module(module_name)
            results = mod.run_tests(
                target_url=target_url,
                api_key=api_key,
                db_host=db_host,
                db_user=db_user,
            )

            all_results['modules'][module_name] = results

            for test in results.get('tests', []):
                all_results['summary']['total_tests'] += 1
                status = test.get('status', 'error')
                if status == 'PASS':
                    all_results['summary']['passed'] += 1
                elif status == 'FAIL':
                    all_results['summary']['failed'] += 1
                else:
                    all_results['summary']['errors'] += 1

        except Exception as exc:
            print(f"ERROR loading/running {module_name}: {exc}")
            traceback.print_exc()
            all_results['modules'][module_name] = {
                'error': str(exc),
                'tests': [],
            }
            all_results['summary']['errors'] += 1

    return all_results


def write_json_report(results, output_dir):
    """Write raw JSON results."""
    ts = datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')
    path = os.path.join(output_dir, f'ai_redteam_results_{ts}.json')
    with open(path, 'w') as f:
        json.dump(results, f, indent=2, default=str)
    print(f"\nJSON report written to: {path}")
    return path


def write_markdown_report(results, output_dir):
    """Generate a human-readable markdown report."""
    ts = datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')
    path = os.path.join(output_dir, f'ai_redteam_report_{ts}.md')
    s = results['summary']

    lines = [
        '# AI Red Team Report',
        f'**Run:** {results["run_timestamp"]}',
        f'**Target:** {results["target"]}',
        '',
        '## Summary',
        f'| Metric | Count |',
        f'|--------|-------|',
        f'| Total tests | {s["total_tests"]} |',
        f'| Passed (injection blocked) | {s["passed"]} |',
        f'| Failed (vulnerability found) | {s["failed"]} |',
        f'| Errors | {s["errors"]} |',
        '',
    ]

    for module_name, module_data in results['modules'].items():
        lines.append(f'## {module_name}')
        lines.append('')

        if 'error' in module_data:
            lines.append(f'**Module error:** {module_data["error"]}')
            lines.append('')
            continue

        lines.append('| Test | Status | Response Preview |')
        lines.append('|------|--------|-----------------|')

        for test in module_data.get('tests', []):
            name = test.get('test_name', 'unknown')
            status = test.get('status', 'ERROR')
            preview = test.get('response_preview', '')[:80].replace('|', '\\|').replace('\n', ' ')
            lines.append(f'| {name} | {status} | {preview} |')

        lines.append('')

    lines.append('---')
    lines.append('*Generated by AI Red Team Framework — Cherokee AI Federation*')

    with open(path, 'w') as f:
        f.write('\n'.join(lines))
    print(f"Markdown report written to: {path}")
    return path


def main():
    parser = argparse.ArgumentParser(description='AI Red Team Test Runner')
    parser.add_argument('--target', required=True, help='LLM Gateway base URL')
    parser.add_argument('--api-key', required=True, help='API key for LLM Gateway')
    parser.add_argument('--db-host', default='192.168.132.222', help='PostgreSQL host (bluefin)')
    parser.add_argument('--db-user', default='claude', help='PostgreSQL user')
    parser.add_argument('--output', default='./results/', help='Output directory for reports')

    args = parser.parse_args()

    os.makedirs(args.output, exist_ok=True)

    # Ensure we can import sibling modules
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

    print("AI Red Team Test Runner — Cherokee AI Federation")
    print(f"Target: {args.target}")
    print(f"DB Host: {args.db_host}")
    print(f"Output: {args.output}")

    results = run_all_tests(
        target_url=args.target,
        api_key=args.api_key,
        db_host=args.db_host,
        db_user=args.db_user,
        output_dir=args.output,
    )

    json_path = write_json_report(results, args.output)
    md_path = write_markdown_report(results, args.output)

    s = results['summary']
    print(f"\n{'='*60}")
    print(f"AI RED TEAM COMPLETE")
    print(f"  Total: {s['total_tests']}  Passed: {s['passed']}  Failed: {s['failed']}  Errors: {s['errors']}")
    print(f"{'='*60}")

    # Exit with non-zero if any failures found
    if s['failed'] > 0:
        print(f"\nWARNING: {s['failed']} vulnerability(ies) detected!")
        sys.exit(1)


if __name__ == '__main__':
    main()
